---
title: "Project Proposal V1"
format: html
editor: visual
---

## Project Proposal

INTRODUCTION: The purpose of this project is to evaluate the role of abiogenic sediments, algae, and colored (chromophoric) dissolved organic matter (CDOM) in the water clarity of Virginia reservoirs. Water clarity is a key property of lakes because it determines the depth to which primary production occurs (i.e., the trophogenic zone; 1, 2). As abiogenic turbidity, algal abundance, and CDOM increase, light penetration decreases due to greater scattering and absorption of photons. As water clarity decreases, submerged aquatic vegetation declines while phytoplankton and algal blooms become more dominant (3, 1). Declines in water clarity cause a shift in lake state from a clear water macrophyte-dominated regime to a light-limited phytoplankton-dominated ecosystem (3). Loss of macrophyte communities diminishes littoral habitat structure and results in further reductions in water clarity due to greater sediment resuspension (5, 6). Increased algal blooms are associated with a range of water quality problems including low dissolved oxygen and the release of toxins harmful to humans and livestock (7, 8).

A 2012 study of algae communities in 46 Virginia reservoirs found the majority to be meso- eutrophic and prone to cyanobacteria (a harmful algal bloom-producing bacteria) (9). Long-term

changes in water clarity may, therefore, serve as a key indicator of trends in lake health. Reservoirs are important components of the hydrologic landscape because they provide a range of ecosystem services such as public water supplies, sources of renewable energy, and opportunities for outdoor recreation. Within the Commonwealth of Virginia, and regionally in the southeastern US, reservoirs are the dominant lake type. A number of studies have examined the factors regulating water clarity in natural lakes, principally in the north temperate zone (4, 14, 15), but few studies have investigated the factors controlling water clarity in reservoirs. We know of no prior studies that have examined long-term trends in water clarity for this important group of lakes. The light climate of reservoirs is likely to be complex and dynamic owing to the multiple factors affecting light attenuation. These include abiogenic sediments (as indicated by Total Suspended Solids; TSS), algae (as indicated by Chlorophyll-a; CHLa), and dissolved color (CDOM). We expect their relative importance to vary among reservoirs, which differ in their geographic setting, and specifically, in relation to land use practices that affect sediment and nutrient inputs (10,4).

We developed hypotheses that consider landscape-scale (ecoregion), seasonal, and intra- lake spatial variation in water clarity. (H-I) We expect that abiogenic sediments will play a

Jackson Barnett Thesis Proposal greater role in light attenuation among reservoirs in the Mountain and Piedmont regions where greater topographic variation results in higher sediment yields. We predict that algae will have a stronger influence on water clarity in lowland areas (Piedmont and Coastal Plain) where greater agricultural activity results in excess nutrient loads. Lastly, we expect that dissolved color will increase in importance in the Coastal Plain where predominantly sandy soils allow greater leaching of CDOM from natural vegetation. (H-II) Seasonally, we expect that CHLa will dominate light attenuation in Summer months when primary production is higher, and TSS will dominate in colder months and other periods with elevated runoff (1). (H-III) Intra-lake spatial variation may be important in reservoirs where upstream areas have high sediment loads due to river inputs, whereas downstream areas experience greater algal blooms due to longer water residence time. A preliminary analysis has allowed us to categorize a small set of lakes as being sediment- vs. algal-dominated based on the strength of univariate regressions between TSS and CHLa with clarity (Secchi depth). We propose to expand upon this analysis by collecting and examining additional data on the primary factors influencing light attenuation in six Virginia reservoirs. Additionally, our examination of these hypotheses will further extend via a historical analysis of the full suite of reservoirs currently monitored by the Virginia Department of Environmental Quality (DEQ) (\~100 lakes). The objective of this is to better assess the drivers of change in water clarity temporally and spatially. In addition to providing insight into the spatial and temporal variations in regulators, this portion will give a broad historical context to the field study results where a more detailed analysis of additional factors can be carried out. This study will help determine what proportion of Virginia reservoirs show trends in water clarity and whether these trends can be linked to changes in CHLa or TSS.

METHODS: The primary methodology of this study will be split into two principal components. Component one is a six-month field study to characterize light attenuation and identify controlling factors (sediment, algae, and CDOM) for six reservoirs across multiple Virginia ecoregions. These data will provide a basis for assessing the relative importance of factors controlling reservoir water clarity, considering both intra-lake (seasonal and spatial) and inter-

Jackson Barnett Thesis Proposal lake variations. Component two will focus on analyzing historical lake water quality data to assess long-term trends in water clarity and its regulating factors. The study sites for the field portion of this study are being chosen from the list of reservoirs sampled by DEQ in the 2024 field season (May-October), with the exceptions of Harrison Lake and Chickahominy Lake. Sites were chosen in part due to their proximity to Richmond, however, represent a range of water clarity conditions that will provide variation in collected data. Data collection for most sites will last six months (May-October), however, Lake Anna will have approximately 18 months of data due to VCU sampling efforts prior to the creation of this study. Table 1, seen below, outlines the potential sites being considered for this study. Key characteristics such as reservoir area, ecoregion, and mean historical CHLa, Secchi Depth, and TSS are shown. These averages were calculated using DEQ data discussed in component two of this proposal. Final considerations of these reservoirs are being based upon the feasibility of riding along with DEQ for data collection during the field sampling season.

Sites will be sampled by boat and a vertical profile of general water quality parameters (dissolved oxygen, specific conductivity, etc.) will be created using a YSI Pro DDS sonde at 1m intervals. A vertical profile of light attenuation data will be recorded using a LI-COR LI-1400 data logger with surface quantum and underwater sensors (LI-190SA and LI-192SA). This measurement will be comprised of underwater irradiance measurements taken in 0.5-1m intervals from the surface through the photic layer. A linear regression of log-transformed downwelling irradiance and lake depth measurements will be used to find the light attenuation coefficients for a given site during sampling (Kd; m-1) (17). Lake/Reservoir Area (acres) Level3_Ecoregion StationID Location

CHLa Mean (ug/L) Secchi Mean (m) TSS Mean (mg/L) Briery Creek Lake 845 Piedmont 2-BRI010.78 BRIERY CREEK LAKE STA.#1 AT DAM PRINCE E 7.12 1.54 3.50 Briery Creek Lake - Piedmont 2-BRI013.12 BRIERY CREEK LAKE UPPER END OF LAKE PRIN 8.43 1.32 3.50 Chickahominy Lake 1230 Southeastern Plains 2-CHK025.15 Chickahominy Reservoir, Station 1 16.78 0.73 4.79 Chickahominy Lake - Southeastern Plains 2-CHK026.94 CHICKAHOMINY LAKE STA #2 UPPER LAKE NEW 12.54 0.82 4.00 Chickahominy Lake - Southeastern Plains 2-CHK029.54 Chickahominy Reservoir 7.63 0.94 4.43 Sandy River Reservoir 740 Piedmont 2-MBN000.96 SANDY RIVER RESERVOIR, MARROWBONE CR AR 11.24 1.15 - Sandy River Reservoir - Piedmont 2-SDY004.27 SANDY RIVER, RESERVOIR, NEAR DAM 11.49 1.14 - Sandy River Reservoir - Piedmont 2-SDY005.85 SANDY RIVER, RESRVOIR, UPPER LAKE STATIO 12.11 1.06 - Swift Creek Reservoir 1700 Piedmont 2-DYC000.19 SWIFT CREEK RESERVOIR STA #2,DRY CREEK A 12.18 0.96 4.79 Swift Creek Lake - Piedmont 2-SFT022.14 SWIFT CREEK LAKE STA #1 NEAR DAM CHESTER 16.81 0.59 9.17 Swift Creek Reservoir - Piedmont 2-SFT031.08 Swift Creek Reservoir, Station 1 11.45 0.99 4.43 Swift Creek Reservoir - Piedmont 2-SFT033.42 SWIFT CREEK RESERVOIR NO. 6 11.50 0.90 4.43 Swift Creek Reservoir - Piedmont 2-SFT034.38 SWIFT CRK RESERVOIR STA #4 UPPER LAKE CH 13.67 0.75 6.29 Harrison Lake 82 Southeastern Plains 2-WER000.02 15 YDS FROM SPILLWAY HARRISON LAKE 10.96 0.71 7.83 Lake Anna 13000 Piedmont 8-NAR034.92 LAKE ANNA (main) - 100 YDS From Dam 4.32 1.83 3.00 Table 1: Potential Field Study Sampling Sites and their Area, Ecoregion, and Mean Historical CHLa, Secchi Depth, and TSS

Jackson Barnett Thesis Proposal A photic zone integrated water sample will be taken using the underwater irradiance data to find the 1% light level at each site. The integrated water sample will comprise 3-5 2 L samples taken at multiple depths within the photic zone. From this sample, water will be analyzed for TN, TP, CDOM, TSS, and CHLa. CHLa samples will be filtered through Whatman GF/A glass filters (0.5-μm nominal pore size), extracted for 18h in buffered acetone, and analyzed on a Turner

Design TD-700 Fluorometer. TSS will be found gravimetrically with pre-weighed, pre- combusted filters (0.5 μm). CDOM samples will be filtered through glass filters (0.5 μm) and

analyzed at wavelengths of 440 nm and 700 nm and a path length of 10cm using a Thermo Scientific dual beam Evolution 200 Series Spectrophotometer. Absorbance coefficients at 440 nm will be corrected with absorbance at 700 nm using methods outlined in Davies-Colley and Vant to account for any discrepancies in absorbance outside of the range of CDOM (16).

The historical portion of this study will use data obtained from DEQ to evaluate long- term trends in water clarity and assess the relative influence of suspended solids and algae on

water clarity. Since 2000, DEQ has collected Secchi depth, TSS, and CHLa data on approximately 100 Virginia reservoirs. Data were collected monthly during May-October, though not all reservoirs are visited annually. For smaller reservoirs, data are collected at a single (near-dam) station, whereas larger reservoirs are monitored at multiple stations located along the longitudinal axis. The 20+ years of data will provide a historical context for assessing changes in water clarity. We will develop univariate linear models and generalized additive models (GAMs) to evaluate concurrent changes in TSS, CHLa, and Secchi depth for each monitoring location. Similarly, GAMS will be used to evaluate changes in TSS, CHLa, CDOM, and light attenuation across sites in the field portion of this study. GAMs will let us view non-linear relationships in the data due to their non-parametric properties (11, 12). This will allow us to depict Secchi depth or light attenuation responses to each variable/predictor, conditioned on all additional variables. Modeling will follow the same process as described in Henderson and Bukaveckas for modeling estuarine light attenuation (13). The predictor variables will be day-of-year and decimal date to view both seasonal and long-term patterns. GAMs will be completed in R using the ‘mgcv’ package. Results will be scaled to the center of the mean for predictor assessment. These results will provide insight into Virginia’s reservoirs, as well as produce a publicly available R program that will be applicable to other state/regional water clarity datasets.

Jackson Barnett Thesis Proposal Results: By characterizing trends in water clarity for over 100 Virginia reservoirs and assessing the factors controlling water clarity, this study will provide important information regarding status and trends for a key lake health variable. The results from this project will benefit lake associations by providing site-specific information, as well as regulatory agencies (i.e., DEQ) seeking to protect lake health through the development and application of numeric water quality criteria. Lastly, the findings will provide a broader contribution to the scientific literature on the light climate of reservoirs and the utility of monitoring data for assessing anthropogenic effects on water clarity. TSS, CHLa, and Secchi data are commonly collected by environmental agencies nationwide; this analysis will establish approaches for using historical and lake survey data to assess factors influencing water clarity. CDOM and light attenuation data are less commonly collected, however, our findings will help to establish the relative importance of their roles in understanding reservoir light environments. Progress to date includes approximately one year of completed data collection from the Lake Anna study site, analysis of CHLa, TSS, and CDOM samples from Lake Anna, and communication with DEQ to receive all historical TSS, CHLa, and Secchi depth data. This data is in the early stages of being vetted, formatted, and QA/QC checked. The development of a general framework for statistical analyses has begun, however, there is still coding and review to be completed before results can be formed and interpreted. Through this project, we hope to inform future management of Virginia's water resources by both regulators and general stakeholders (e.g., lake associations). As harmful algal blooms increase in Virginia, accessible information as to their influence on light environments will become more relevant. Already, we have seen this through our collaboration with the Lake Anna Civic Association and Lake Anna property owners. Communication with these stakeholders has highlighted the need for more information on water clarity and the extent to which this is influenced by algal blooms.

Jackson Barnett Thesis Proposal References

\[1\] Thornton, K. W., Kimmel, B. L., & Payne, F. E. (1991). Reservoir limnology: ecological perspectives. John Wiley & Sons. \[2\] Davies-Colley, R.J., and D.G. Smith. (2001). Turbidity, suspended sediment, and water clarity: A review. Journal of the American Water Resources Association, 37 (5), 1085– 1101. \[3\] King, L., Brahney, J., Daly, S., Paul, M. J., Salk, K. R., & Brothers, S. (2023). Primary production modeling identifies restoration targets for shifting shallow, eutrophic lakes to clear-water regimes. Freshwater Science, 42(1), 44-57. \[4\] Squires, M. M., & Lesack, L. F. (2003). Spatial and temporal patterns of light attenuation among lakes of the Mackenzie Delta. Freshwater biology, 48(1), 1-20. \[5\] James, W. F., Best, E. P., & Barko, J. W. (2004). Sediment resuspension and light attenuation in Peoria Lake: can macrophytes improve water quality in this shallow system?. Hydrobiologia, 515, 193-201. \[6\] United States Environmental Protection Agency. (2010). Chesapeake Bay Total Maximum Daily Load for Nitrogen, Phosphorus and Sediment. US Environmental Protection Agency, 93. \[7\] Backer, L. C. (2012). Freshwater algal blooms & public health. Lake line/North American Lake Management Society, 32(3), 7. \[8\] Funari, E, & Testai,E. (2008). Human Health Risk Assessment Related to Cyanotoxins Exposure, Critical Reviews in Toxicology, 38:2, 97-125, DOI: 10.1080/10408440701749454 \[9\] Marshall, H.G. (2013). Phytoplankton in Virginia lakes and reservoirs. Virginia Journal of Science, 64(1-2), 3-15. \[10\] Loiselle, S. A., Azza, N., Cozar, A., Bracchini, L., Tognazzi, A., Dattilo, A., & Rossi, C. (2008). Variability in factors causing light attenuation in Lake Victoria. Freshwater Biology, 53(3), 535-545. \[11\] Morton, R., and B.L. Henderson. (2008). Estimation of non-linear trends in water quality: An improved approach using generalized additive models. Water Resources Research, 44: W07420.

Jackson Barnett Thesis Proposal

\[12\] Yang, G., and D.L. Moyer. (2020). Estimation of non-linear water quality trends in high- frequency monitoring data. Science of the Total Environment 715: 136686.

\[13\] Henderson, R., Bukaveckas, P.A. (2022). Factors governing light attenuation in upper segments of the James and York estuaries and their influence on primary producers. Estuaries and Coasts, 45, 470–484. \[14\] Sanderson, B. L. (1998). Factors regulating water clarity in northern Wisconsin lakes (Order No. 9910427) \[Doctoral dissertation, University of Wisconsin-Madison\]. ProQuest Dissertations & Theses Global. (304456486). \[15\] James, W. F., Best, E. P., & Barko, J. W. (2004). Sediment resuspension and light attenuation in Peoria Lake: can macrophytes improve water quality in this shallow system?. Hydrobiologia, 515, 193-201. \[16\] Davies‐Colley, R. J., & Vant, W. N. (1987). Absorption of light by yellow substance in freshwater lakes. Limnology and oceanography, 32(2), 416-425. \[17\] Kirk, J.T.O. (2011). Light and Photosynthesis in aquatic ecosystems, 3rd ed. New York, NY: Cambridge University Press.
